name: Pull Request Check

on:
  push:
    branches:
      - master
      - "!maintenance/lists-update"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: ["23.x"]
        elixir: ["1.11.x"]

    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - uses: actions/cache@v2
        with:
          path: deps
          id: deps-cache
          key: deps-${{ runner.os }}-${{matrix.otp}}-${{matrix.elixir}}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            deps-${{ runner.os }}-${{matrix.otp}}-${{matrix.elixir}}-

      - uses: actions/cache@v2
        with:
          path: _build/test
          id: build-cache
          key: build-test-${{ runner.os }}-${{matrix.otp}}-${{matrix.elixir}}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            build-test-${{ runner.os }}-${{matrix.otp}}-${{matrix.elixir}}-

      - name: Install package managers
        run: |
          mix local.rebar --force
          mix local.hex --force

      - name: Download deps
        if: steps.cache.deps-cache.cache-hit != 'true'
        run: mix deps.get

      - name: Check mix.lock (fix mix deps.clean --unused --unlock)
        run: mix deps.unlock --check-unused

      - run: mix format --check-formatted

      - name: Compile deps
        if: steps.cache.build-cache.cache-hit != 'true'
        run: mix deps.compile

      - run: mix compile --warnings-as-errors

      - run: mix test

      - name: Clean up unused deps (used for cache)
        run: mix deps.clean --unused --unlock
